export const users = [
  {
    userName: "John",
    email: "user1@example.com",
    password: "password",
    imageUrl: "",
    courses: [1, 2, 3, 4, 5, 6],
  },
  {
    userName: "Dean",
    email: "user2@example.com",
    password: "password",
    imageUrl: "",
    courses: [1, 2],
  },
  {
    userName: "Sam",
    email: "user3@example.com",
    password: "password",
    imageUrl: "",
    courses: [3, 4, 5],
  },
  {
    userName: "Bobby",
    email: "user4@example.com",
    password: "password",
    imageUrl: "",
    courses: [6],
  },
  {
    userName: "Castiel",
    email: "user5@example.com",
    password: "password",
    imageUrl: "",
    courses: [1, 4, 5, 6],
  },
  {
    userName: "Jack",
    email: "user6@example.com",
    password: "password",
    imageUrl: "",
    courses: [2, 3],
  },
  {
    userName: "Crowly",
    email: "user7@example.com",
    password: "password",
    imageUrl: "",
    courses: [1, 6],
  },
  {
    userName: "Lucy",
    email: "user8@example.com",
    password: "password",
    imageUrl: "",
    courses: [3, 4],
  },
];
